matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "WPXukULFRPxdzkTYVdRmv9Cp00fSIAncSmgATCB0roFsojHh0Qvcnt3EjW0nsQ6huocI8kiuchhtIg/oKXljTQeBw3jMfI8VUhpGf2uvGiZI/sG50uFZSvPepB9OTUDohlsTUkhm7hjEAYCqCoaO1lEnOZKrTZobF+UZz6ICjuCYnmc0fvJDpPjMZ7sWaM/16SOsQQk3ATcJs2bzyPlJFsYiPQIY7gyoBxdcXpojDtNPZx70DisRcUhCl//Z0jqx1UQlrsG1hRSSoyRr534GvfLDJvXMZ2aCmOU2b7hz2ZDAhLMpIV9VmtYXlJxz9lRNtcI9NVqdis5qXtTPE3A5TIQyesRMiePXMCV+/mEa6nw8ghQrLKSrIbfkwcS6kwfiTV3ZrGEZ69QHaiBj5pY1GJw5HI97tK7iFxDqaRziVPxW/yS7BSWvd8fWRvVERkPONkypdrSmD5q5cMnnKxNP55GzkvOBrbj5XqSTXMnuPiY0mqk9GerHjH2iIfTTo9e5BOZIcFnqZlsz/kGIxREeSijkt0Blw+DjxGBK/z5FT2kO3PqUR7dCKmz1g6g9sVTHsXDicq3dYWWCZKWmkcl9tDgYGEmBdDohqvwLyyd+krqfwaVVsYelRwNajr5hNS2/XwaqUE6NTBUE2Afi9vIvSnT5kIoUcJJjKfW6OgQ3flg="
    before_install:
    - cd frontend
    install:
    - yarn install
    - npm install
    script:
    - ./node_modules/.bin/eslint src/
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python:
    - '3.6'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "WPXukULFRPxdzkTYVdRmv9Cp00fSIAncSmgATCB0roFsojHh0Qvcnt3EjW0nsQ6huocI8kiuchhtIg/oKXljTQeBw3jMfI8VUhpGf2uvGiZI/sG50uFZSvPepB9OTUDohlsTUkhm7hjEAYCqCoaO1lEnOZKrTZobF+UZz6ICjuCYnmc0fvJDpPjMZ7sWaM/16SOsQQk3ATcJs2bzyPlJFsYiPQIY7gyoBxdcXpojDtNPZx70DisRcUhCl//Z0jqx1UQlrsG1hRSSoyRr534GvfLDJvXMZ2aCmOU2b7hz2ZDAhLMpIV9VmtYXlJxz9lRNtcI9NVqdis5qXtTPE3A5TIQyesRMiePXMCV+/mEa6nw8ghQrLKSrIbfkwcS6kwfiTV3ZrGEZ69QHaiBj5pY1GJw5HI97tK7iFxDqaRziVPxW/yS7BSWvd8fWRvVERkPONkypdrSmD5q5cMnnKxNP55GzkvOBrbj5XqSTXMnuPiY0mqk9GerHjH2iIfTTo9e5BOZIcFnqZlsz/kGIxREeSijkt0Blw+DjxGBK/z5FT2kO3PqUR7dCKmz1g6g9sVTHsXDicq3dYWWCZKWmkcl9tDgYGEmBdDohqvwLyyd+krqfwaVVsYelRwNajr5hNS2/XwaqUE6NTBUE2Afi9vIvSnT5kIoUcJJjKfW6OgQ3flg="
    before_install:
    - cd backend
    install:
    - pip3 install django
    - pip3 install pylint
    script:
    - pylint **/*.py
    - sonar-scanner